config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'watch_with_style_lists#index'
  resources :watch_with_style_lists, only: [:index, :new, :show]
  resources :watch_with_style_lists do 
    resources :watch_with_style_bookmarks, only: [:new, :create]
  end
  resources :watch_with_style_bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/models/watch_with_style_bookmark.rb
class WatchWithStyleBookmark < ApplicationRecord
  belongs_to :watch_with_style_movie
  belongs_to :watch_with_style_list
  validates :watch_with_style_movie, uniqueness: { scope: :watch_with_style_list }
  validates :comment, length: { minimum: 6 }
end

app/models/watch_with_style_list.rb
class WatchWithStyleList < ApplicationRecord
  has_many :watch_with_style_bookmarks, dependent: :destroy
  has_many :watch_with_style_movies, through: :watch_with_style_bookmarks
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/watch_with_style_movie.rb
class WatchWithStyleMovie < ApplicationRecord
  has_many :watch_with_style_bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/watch_with_style_bookmarks_controller.rb
class WatchWithStyleBookmarksController < ApplicationController
  def new
    @bookmark = WatchWithStyleBookmark.new
  end

  def create
    @list = WatchWithStyleList.find(params[:watch_with_style_list_id])
    @bookmark = WatchWithStyleBookmark.new(bookmark_params)
    @bookmark.watch_with_style_list = @list
    if @bookmark.save
      redirect_to watch_with_style_list_path(@list)
    else
      render 'watch_with_style_lists/show'
    end
  end

  def destroy
    @bookmark = WatchWithStyleBookmark.find(params[:id])
    @bookmark.delete
    redirect_to watch_with_style_list_path(@bookmark.watch_with_style_list)
  end

  private
  
  def bookmark_params
    params.require(:watch_with_style_bookmark).permit(:comment, :watch_with_style_movie_id)
  end
end

app/controllers/watch_with_style_lists_controller.rb
class WatchWithStyleListsController < ApplicationController
  def index
    @lists = WatchWithStyleList.all
    @list = WatchWithStyleList.new
  end

  def show
    @bookmark = WatchWithStyleBookmark.new
    @list = WatchWithStyleList.find(params[:id])
  end

  def new
    @list = WatchWithStyleList.new
  end

  def create
    @list = WatchWithStyleList.new(list_params)
    if @list.save
      redirect_to watch_with_style_watch_with_style_lists_path
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:watch_with_style_list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module WatchWithStyleBookmarksHelper
end

app/helpers/lists_helper.rb
module WatchWithStyleListsHelper
end

app/helpers/watch_with_style_bookmarks_helper.rb
module WatchWithStyleBookmarksHelper
end

app/helpers/watch_with_style_lists_helper.rb
module WatchWithStyleListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Bookmarks#new</h1>
<p>Find me in app/views/bookmarks/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchWatchWithStyleList</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="d-flex flex-column p-4" style="height: 100vh">
  <div class="">
    <h1 class="mb-5">Watch with style 🍸</h1>
  </div>
  <h4 class="">Discover our movie selection</h4>
  <div class="carousel-container flex-grow-1">
    <div class="carousel">
      <div class="carousel--wrap">
      <% @lists.each do |list| %>
        <div class="carousel--item py-1 px-3">
          <%= link_to list_path(list) do %>
            <% if list.photo.attached? %>
              <figure><%= cl_image_tag list.photo.key %></figure>
            <% else %>
              <figure><img src="<%= "https://picsum.photos/seed/#{list.name}/500/300" %>" alt="" /></figure>
            <% end %>
            <h2><%= list.name %></h2>
          <% end %>
        </div>
      <% end %>
      </div>
      <div class="carousel--progress d-none">
        <div class="carousel--progress-bar"></div>
      </div>
    </div>
  </div>
  <div class="mt-5">
    <h4 class="mt-4">Or create your own</h4>
    <div class="mt-3">
      <%= render 'form', list: @list %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="container pt-5">
  <h1 class="my-5"><%= @list.name %> with style 🍹</h1>
  <div class="row">
    <div class="col-9 mt-5">
      <div class="d-flex align-items-center justify-content-center h-100">
        <% if @list.bookmarks.empty? %>
          <h4>Oops, no movies yet...<br>Add one 👉</h4>
        <% end %>
        <% @list.bookmarks.each do |bookmark| %>
          <div class="mx-5 text-center">
            <%= image_tag bookmark.movie.poster_url, width: '100px' %>
            <p><%= bookmark.movie.title %></p>
            <%= link_to "Not cool?", bookmark_path(bookmark), method: :delete, data: { confirm: 'Sure or what?' }, class: "btn btn-outline-light" %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-3 mt-5">
      <h4>Maybe another one?</h4>
      <%= render "bookmarks/form", list: @list, bookmark: @bookmark %>
    </div>
  </div>
  <%= link_to "Back to lists", lists_path, class: "btn text-light mt-5" %>
</div>

app/views/watch_with_style_bookmarks/_form.html.erb
<%= simple_form_for [list, bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :watch_with_style_movie %>
  <%= f.button :submit %>
<% end %>

app/views/watch_with_style_bookmarks/new.html.erb
<h1>WatchWithStyleBookmarks#new</h1>
<p>Find me in app/views/bookmarks/new.html.erb</p>

app/views/watch_with_style_lists/_form.html.erb
<%= simple_form_for list, html: {class: "w-25"} do |f| %>
  <%= f.input :name, input_html: { placeholder: "Your dandy name"}, label: false, wrapper_html: { class: 'm-0'} %>
  <%= f.input :photo, as: :file, label: 'A dandy image maybe?', label_html: {class: "mt-3"} %>
  <%= f.submit 'Start', class: "btn btn-dark mt-3" %>
<% end %>

app/views/watch_with_style_lists/index.html.erb
<div class="d-flex flex-column p-4" style="height: 100vh">
  <div class="">
    <h1 class="mb-5">Watch with style 🍸</h1>
  </div>
  <h4 class="">Discover our movie selection</h4>
  <div class="carousel-container flex-grow-1">
    <div class="carousel">
      <div class="carousel--wrap">
      <% @lists.each do |list| %>
        <div class="carousel--item py-1 px-3">
          <%= link_to watch_with_style_list_path(list) do %>
            <% if list.photo.attached? %>
              <figure><%= cl_image_tag list.photo.key %></figure>
            <% else %>
              <figure><img src="<%= "https://picsum.photos/seed/#{list.name}/500/300" %>" alt="" /></figure>
            <% end %>
            <h2><%= list.name %></h2>
          <% end %>
        </div>
      <% end %>
      </div>
      <div class="carousel--progress d-none">
        <div class="carousel--progress-bar"></div>
      </div>
    </div>
  </div>
  <div class="mt-5">
    <h4 class="mt-4">Or create your own</h4>
    <div class="mt-3">
      <%= render 'form', list: @list %>
    </div>
  </div>
</div>

app/views/watch_with_style_lists/show.html.erb
<div class="container pt-5">
  <h1 class="my-5"><%= @list.name %> with style 🍹</h1>
  <div class="row">
    <div class="col-9 mt-5">
      <div class="d-flex align-items-center justify-content-center h-100">
        <% if @list.watch_with_style_bookmarks.empty? %>
          <h4>Oops, no movies yet...<br>Add one 👉</h4>
        <% end %>
        <% @list.watch_with_style_bookmarks.each do |bookmark| %>
          <div class="mx-5 text-center">
            <%= image_tag bookmark.watch_with_style_movie.poster_url, width: '100px' %>
            <p><%= bookmark.watch_with_style_movie.title %></p>
            <%= link_to "Not cool?", watch_with_style_bookmark_path(bookmark), method: :delete, data: { confirm: 'Sure or what?' }, class: "btn btn-outline-light" %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-3 mt-5">
      <h4>Maybe another one?</h4>
      <%= render "watch_with_style_bookmarks/form", list: @list, bookmark: @bookmark %>
    </div>
  </div>
  <%= link_to "Back to lists", watch_with_style_lists_path, class: "btn text-light mt-5" %>
</div>